Fix paging example
sreeise/graph-rs pull request #407
Opened 2023-04-05 10:05 UTC by DevLazio

Fix #406

2023-04-05 18:43 UTC, sreeise requested changes
One small change. Everything else looks good. Thanks for the PR fix.

2023-04-05 18:43 UTC, sreeise commented on examples/paging.rs
> +use serde::Serialize;
```suggestion
#[macro_use]
extern crate serde;

use graph_rs_sdk::*;
```

2023-04-05 18:45 UTC, sreeise commented
If you want to. You can change the examples/next_link directory to examples/paging and add your example in there. Thats what that directory was meant to be. But I just forgot with so many changes that went into 1.0.0

2023-04-06 12:58 UTC, sreeise commented on examples/paging.rs
> +use serde::Serialize;
Gonna go ahead and commit this and get the example merged in.

2023-04-06 12:59 UTC, merged

2023-04-06 13:08 UTC, DevLazio commented
Sorry for the delay, was busy this morning. I see you merged it already, thanks.

2023-04-06 13:35 UTC, sreeise commented
> 

No problem at all. Your all good.  I just wanted to go ahead and get the next version update in so thats why I merged it. Thank you for the fix 🚀